name: ImageBuild

on:
  # mainブランチにpushされ、自動テストが完了したら実行するワークフロー
  workflow_run:
    workflows:
      - pytest
    branches:
      - main
    types:
      - completed

env:
  TAG: echo "$(TZ=Asia/Tokyo date +%Y%m%d%H%M%S)"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # 前のワークフローが失敗している場合は終了
      - name: Check previous workflow status.
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo '::error::Previous workflow was failed'
          exit 1
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-sample-api:${{ env.TAG }}
      - name: Add git tag
      - run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
